version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
general:
  branches:
    only:
      - development
      
test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: "A first hello test"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      
